"""
Regenerates result figures without re-running the full experiment pipeline.

- Comparison charts (model_comparison_f1, scenario_impact) are built from the
  already-saved results/experiment_full_raw.csv (1710 runs).
- DL representative figures (confusion matrix + ROC/PR for LSTM on SKAB_Fold1)
  require probability outputs, so one LSTM training run is repeated with the
  same data/seed used in the main pipeline (multivariate input, seed=42).
- Automata figures (state diagram, transition heatmap, param heatmap, conf
  matrix, curves) are NOT touched here — they were regenerated by the last
  full main.py run and the automata results are deterministic/unchanged.
"""
import logging

import pandas as pd

from src.utils.config_loader import load_config
from src.data.data_loader_skab import SKABDataLoader
from src.models.dl_models import DLAnomalyDetector
from src.models.model_registry import get_model_class
from src.visualization.visualization_and_stats import (
    plot_model_comparison,
    plot_scenario_impact,
    plot_confusion_matrix,
    plot_roc_pr_curves,
)
from main import set_seed

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

cfg = load_config()

# --- 1. Aggregate comparison charts from saved results ---
df = pd.read_csv("results/experiment_full_raw.csv")
plot_model_comparison(df, metric="f1")
plot_scenario_impact(df, metric="f1")

# --- 2. DL representative figures (same combo main.py Step 6 captures:
#        first DL model, first dataset, Original scenario, first seed) ---
m_name = cfg["models"]["dl"][0]
seed = cfg["training"]["seeds"][0]

loader = SKABDataLoader()
X_tr, X_te, y_tr, y_te = next(iter(loader.get_folds(n_splits=5, apply_pca=False)))
split = int(len(X_tr) * 0.8)

set_seed(seed)
detector = DLAnomalyDetector(get_model_class(m_name), config=cfg)
detector.fit(X_tr[:split], y_tr[:split], X_tr[split:], y_tr[split:])
metrics = detector.get_metrics(X_te, y_te, return_outputs=True)

suffix = f"{m_name}_SKAB_Fold1"
plot_confusion_matrix(metrics["y_true"], (metrics["y_prob"] > 0.5).astype(int), suffix)
plot_roc_pr_curves(metrics["y_true"], metrics["y_prob"], suffix)

logging.info(
    f"{suffix}: f1={metrics['f1']:.4f} acc={metrics['accuracy']:.4f} "
    f"prec={metrics['precision']:.4f} rec={metrics['recall']:.4f}"
)
logging.info("Figure regeneration complete -> results/figures/")
